language: java
jdk: oraclejdk8

branches:
  only: 
    - master

before_install: gradle clean release -DbuildNumber=$TRAVIS_BUILD_NUMBER
  
before_deploy:
 - export TRAVIS_TAG="1.$TRAVIS_BUILD_NUMBER"
 - git config --local user.name "$USER_NAME"
 - git config --local user.email "$USER_EMAIL"
 - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"
 
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  overwrite: true
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - build/dist/tweetsched-cron-1.$TRAVIS_BUILD_NUMBER.zip
  on:
    branch: master
    repo: Tweetsched/tweetsched-cron

notifications:
  email:
    on_success: never
    on_failure: always