language: java
jdk: oraclejdk8

script:
  mvn package

after_success:
  - "./scripts/deploy.sh"
  
branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always
