language: java
jdk: oraclejdk8

branches:
  only: 
    - master

before_install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER
  
notifications:
  email:
    on_success: never
    on_failure: always
